// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ACM Global Solutions - AI-Powered Lead Conversion Platform",
  description: "Transform your business with AI automation that responds, qualifies, and converts leads within 60 seconds. Multilingual support in English, Portuguese, and Spanish.",
  keywords: "AI automation, lead conversion, customer engagement, multilingual AI, business automation, lead qualification",
  authors: [{ name: "ACM Global Solutions" }],
  openGraph: {
    title: "ACM Global Solutions - AI Solutions. Powered by Innovation.",
    description: "Empower your service business to respond, qualify, and convert leads within 60 seconds using our premium AI-automation platform.",
    type: "website",
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: "ACM Global Solutions - AI-Powered Lead Conversion",
    description: "Transform your business with AI automation that converts leads in 60 seconds.",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}